### ISSUE TITLE
Need "Save" floppy icon

### ISSUE THREAD

**Issue by WoozyG** [vaadin/vaadin-icons#30] opened 2017-03-14 23:09 UTC
Users are expecting it, even when "save" is actually to the cloud.  Until the general population has converted, an old floppy is a good icon to have.

**Comment by jouni** [comment] 2017-03-15 07:58
Thanks for the request!

See issue #26 which is an exact duplicate of this. So, we are not planning to add a floppy disk icon.

I agree that the icon would be useful in certain limited use cases, where your users are primarily older people and you can’t afford the visual space for the word “Save” and can only use an icon button.

I could also argue, that by using the floppy icon we are enforcing the metaphor even for younger generation users, and would be perpetuating it unnecessarily.

Are you using the icons with Vaadin Framework, Polymer or with something else?

**Comment by WoozyG** [comment] 2017-03-15 15:50
Oops, sorry I didn't see the previous issue and discussion.  I agree moving away from an icon without a physical reference for younger users is good.  Our users are older and less tech savvy, however. I'll train them on the cloud icons instead.

**Closed as completed** 2017-03-15 16:38 UTC
